# Generated by Django 3.1.7 on 2021-03-22 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210322_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime(2021, 3, 22, 18, 25, 24, 54883)),
        ),
    ]
